### ISSUE TITLE
Include JMapper in tests

### ISSUE THREAD

**Issue by avurro** [arey/java-object-mapper-benchmark#4]
Hi,

I read your article where you compare several mappers,  I think that you can achieve interesting results by adding JMapper to the comparison.

https://github.com/jmapper-framework/jmapper-core

(i'm the founder)

**Comment by arey** [comment]
Hi @avurro, I didn't know JMapper. It could be interesting to add it to my benchmark. Do you want to contribute by implementing the OrdeMapper interfarce?

**Comment by avurro** [comment]
Ok @arey
